"""Controlled vocabulary for structurally describing a water measurement context."""

from enum import Enum


class WaterPurpose(str, Enum):
    HUMAN_CONSUMPTION = "HUMAN_CONSUMPTION"
    WATER_BODY_QUALITY = "WATER_BODY_QUALITY"
    TREATMENT_AND_SUPPLY_OPERATION = "TREATMENT_AND_SUPPLY_OPERATION"
    EFFLUENT_DISCHARGE = "EFFLUENT_DISCHARGE"
    OTHER_GOVERNED = "OTHER_GOVERNED"


class WaterStateOrStage(str, Enum):
    RAW_WATER = "RAW_WATER"
    IN_TREATMENT = "IN_TREATMENT"
    TREATED_WATER = "TREATED_WATER"
    DISTRIBUTED_WATER = "DISTRIBUTED_WATER"
    POINT_OF_USE_WATER = "POINT_OF_USE_WATER"
    AMBIENT_WATER_BODY = "AMBIENT_WATER_BODY"
    EFFLUENT = "EFFLUENT"
    OTHER_GOVERNED = "OTHER_GOVERNED"


class SamplingPointType(str, Enum):
    SOURCE_ABSTRACTION = "SOURCE_ABSTRACTION"
    TREATMENT_INLET = "TREATMENT_INLET"
    TREATMENT_PROCESS_POINT = "TREATMENT_PROCESS_POINT"
    FILTER_OUTLET = "FILTER_OUTLET"
    TREATMENT_OUTLET = "TREATMENT_OUTLET"
    STORAGE_POINT = "STORAGE_POINT"
    DISTRIBUTION_NETWORK_POINT = "DISTRIBUTION_NETWORK_POINT"
    POINT_OF_USE = "POINT_OF_USE"
    AMBIENT_WATER_BODY_POINT = "AMBIENT_WATER_BODY_POINT"
    EFFLUENT_POINT = "EFFLUENT_POINT"
    RECEIVING_WATER_POINT = "RECEIVING_WATER_POINT"
    OTHER_GOVERNED = "OTHER_GOVERNED"


class EvaluationScope(str, Enum):
    NORMATIVE = "NORMATIVE"
    OBSERVATIONAL_NON_NORMATIVE = "OBSERVATIONAL_NON_NORMATIVE"
    RECORD_ONLY = "RECORD_ONLY"
